services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: ms-catalog_db
    environment:
      POSTGRES_DB: ms-catalog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "6432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Node.js Application

  redis:
    image: redis:7
    container_name: ms-catalog_redis
    ports:
      - "7379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms-catalog_app
    ports:
      - "5001:4001"
    environment:
      - DATABASE_URL=postgres://postgres:1234@postgres:5432/ms-catalog
      - PORT=5001
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres

volumes:
  postgres_data: