version: '3.8'
services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: ms-catalog_postgres
    environment:
      POSTGRES_DB: ms-catalog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "6432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Node.js Application

  redis:
    image: redis:7
    container_name: ms-catalog_redis
    ports:
      - "7379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms-catalog_app
    ports:
      - "5001:4001"
    environment:
      DATABASE_URL: postgres://postgres:1234@postgres:5432/ms-catalog
      PORT: 4001
      NODE_ENV: production
      REDIS_URL: redis://redis:6379
      CACHE_EXPIRY: 3600
      RETRY_ATTEMPTS: 3
      RETRY_DELAY: 1000
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    command: npm run dev

volumes:
  postgres_data: