services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: ms-catalog_db
    environment:
      POSTGRES_DB: microservicios
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Node.js Application

  redis:
    image: redis:7
    container_name: ms-catalog_redis
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    environment:
      - DATABASE_URL=postgres://postgres:1234@postgres:5432/microservicios
      - PORT=4001
    depends_on:
      - postgres

volumes:
  postgres_data: